name: upload-cve-reports
on: 
  workflow_dispatch:
    inputs:
      pathToCveFile:
        description: The path starting from the root of the repository to the CVE file that should be processed
      target:
        type: choice
        options:
        - production
        - test

jobs:
  Taking-pull-request-file:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Install dependencies and build
        run: |
          npm install  

      - name: Publish CVE
        run: |
          node src/index.js ${{ inputs.pathToCveFile }} ${{ inputs.target }} ${{ secrets.YOUR_API_KEY }} ${{ secrets.YOUR_API_USER }} ${{ secrets.YOUR_API_ORG }}
